# Generated by Django 4.2.30 on 2026-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], max_length=20, verbose_name='Civil Status')),
                ('purok', models.CharField(max_length=150, verbose_name='Purok / Address')),
                ('occupation', models.CharField(blank=True, default='N/A', max_length=150, verbose_name='Occupation')),
                ('is_voter', models.BooleanField(default=False, verbose_name='Registered Voter')),
                ('contact_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Contact Number')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ['-date_created'],
            },
        ),
    ]
