# Generated by Django 4.2.30 on 2026-09-28 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlotterCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='Case No.')),
                ('complainant_name', models.CharField(max_length=150, verbose_name='Complainant')),
                ('complainant_address', models.CharField(max_length=255, verbose_name='Complainant Address')),
                ('respondent_name', models.CharField(max_length=150, verbose_name='Respondent')),
                ('respondent_address', models.CharField(max_length=255, verbose_name='Respondent Address')),
                ('incident_type', models.CharField(max_length=100, verbose_name='Incident Type')),
                ('incident_location', models.CharField(blank=True, default='', max_length=255, verbose_name='Incident Location')),
                ('details', models.TextField(blank=True, default='', verbose_name='Complaint Details')),
                ('status', models.CharField(choices=[('Pending', 'Pending Investigation'), ('Scheduled', 'Hearing Scheduled'), ('Settled', 'Settled (Amicable)'), ('Referred', 'Referred to Court')], default='Pending', max_length=30, verbose_name='Status')),
                ('date_filed', models.DateTimeField(auto_now_add=True, verbose_name='Date Filed')),
            ],
            options={
                'verbose_name': 'Blotter Case',
                'verbose_name_plural': 'Blotter Cases',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_number', models.CharField(max_length=50, unique=True, verbose_name='Household No. / ID')),
                ('purok', models.CharField(choices=[('Purok 1', 'Purok 1'), ('Purok 2', 'Purok 2'), ('Purok 3', 'Purok 3'), ('Purok 4', 'Purok 4'), ('Purok 5', 'Purok 5'), ('Purok 6', 'Purok 6'), ('Purok 7', 'Purok 7'), ('Purok 8', 'Purok 8'), ('Purok 9', 'Purok 9'), ('Purok 10', 'Purok 10')], max_length=100, verbose_name='Purok')),
                ('complete_address', models.CharField(max_length=255, verbose_name='Complete Address')),
                ('head_name', models.CharField(max_length=150, verbose_name='Householder / Head of Family')),
                ('contact_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Number')),
                ('members_count', models.PositiveIntegerField(default=1, verbose_name='Number of Household Members')),
                ('house_type', models.CharField(choices=[('Concrete', 'Concrete'), ('Semi-Concrete', 'Semi-Concrete'), ('Wood', 'Wood / Timber'), ('Bamboo / Light Materials', 'Bamboo / Nipa / Light Materials'), ('Makeshift / Salvaged', 'Makeshift / Salvaged Materials')], default='Concrete', max_length=50, verbose_name='Type of House')),
                ('housing_ownership', models.CharField(choices=[('Owned (House & Lot)', 'Owned (House & Lot)'), ('Owned House, Rented Lot', 'Owned House, Rented Lot'), ('Rented', 'Rented'), ('Living with Relatives (Rent-free)', 'Living with Relatives (Rent-free)'), ('Rent-free with Consent', 'Rent-free with Owner Consent'), ('Informal Settler', 'Informal Settler')], default='Owned (House & Lot)', max_length=50, verbose_name='Housing Ownership')),
                ('water_source', models.CharField(choices=[('Level III - Piped Water Connection', 'Level III - Piped Water Connection'), ('Level II - Communal Faucet / Deep Well', 'Level II - Communal Faucet / Deep Well'), ('Level I - Protected Well / Spring', 'Level I - Protected Well / Spring'), ('Water Refilling Station / Mineral', 'Water Refilling Station / Mineral'), ('Shared / Dug Well', 'Shared / Dug Well')], default='Level III - Piped Water Connection', max_length=60, verbose_name='Water Source')),
                ('electricity', models.CharField(choices=[('Legal Connection (Utility)', 'Legal Connection (Utility)'), ('Shared Connection / Sub-meter', 'Shared Connection / Sub-meter'), ('Solar Power', 'Solar Power'), ('Generator', 'Generator'), ('None / Kerosene / Candle', 'None / Kerosene / Candle')], default='Legal Connection (Utility)', max_length=50, verbose_name='Electricity')),
                ('toilet_facility', models.CharField(choices=[('Water-sealed Flush', 'Water-sealed Flush (Sewerage/Septic)'), ('Pour-flush Toilet', 'Pour-flush Toilet'), ('Ventilated Improved Pit (VIP)', 'Ventilated Improved Pit (VIP) Latrine'), ('Open Pit Latrine', 'Open Pit Latrine'), ('Shared / Communal Toilet', 'Shared / Communal Toilet'), ('No Toilet Facility', 'No Toilet Facility')], default='Water-sealed Flush', max_length=60, verbose_name='Toilet Facility')),
                ('household_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Relocated', 'Relocated')], default='Active', max_length=30, verbose_name='Household Status')),
                ('verification_status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Verification', 'Pending Verification'), ('Approved', 'Approved'), ('Returned for Correction', 'Returned for Correction')], default='Draft', max_length=30, verbose_name='Verification Status')),
                ('admin_remarks', models.TextField(blank=True, default='', verbose_name='Admin Remarks / Correction Notes')),
                ('date_profiled', models.DateTimeField(auto_now_add=True, verbose_name='Date Profiled')),
                ('date_verified', models.DateTimeField(blank=True, null=True, verbose_name='Date Verified')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('profiled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiled_households', to=settings.AUTH_USER_MODEL, verbose_name='Profiled By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_households', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Household Profile',
                'verbose_name_plural': 'Household Profiles',
                'ordering': ['-date_profiled'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Resident ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=80, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Last Name')),
                ('full_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Full Name')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Age')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Sex')),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Live-in / Common-law', 'Live-in / Common-law')], default='Single', max_length=30, verbose_name='Civil Status')),
                ('relationship_to_head', models.CharField(choices=[('Head', 'Household Head'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Relative', 'Other Relative'), ('Non-Relative', 'Non-Relative / Boarder / Househelp')], default='Head', max_length=50, verbose_name='Relationship to Household Head')),
                ('educational_attainment', models.CharField(choices=[('No Formal Education', 'No Formal Education'), ('Elementary Undergraduate', 'Elementary Undergraduate'), ('Elementary Graduate', 'Elementary Graduate'), ('High School Undergraduate', 'High School Undergraduate'), ('High School Graduate', 'High School Graduate'), ('Senior High School', 'Senior High School'), ('Vocational / TVET', 'Vocational / TVET'), ('College Undergraduate', 'College Undergraduate'), ('College Graduate', 'College Graduate (Bachelor)'), ('Post-Graduate', 'Post-Graduate (Master / Doctorate)')], default='High School Graduate', max_length=80, verbose_name='Educational Attainment')),
                ('occupation', models.CharField(blank=True, default='N/A', max_length=120, verbose_name='Occupation')),
                ('employment_status', models.CharField(choices=[('Employed (Private)', 'Employed (Private)'), ('Employed (Government)', 'Employed (Government)'), ('Self-Employed / Business', 'Self-Employed / Business'), ('Informal / Daily Wage', 'Informal / Daily Wage'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Retired / Pensioner', 'Retired / Pensioner'), ('Homemaker / Housewife', 'Homemaker / Housewife'), ('OFW', 'Overseas Filipino Worker (OFW)')], default='Employed (Private)', max_length=50, verbose_name='Employment Status')),
                ('contact_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Number')),
                ('residency_status', models.CharField(choices=[('Permanent Resident', 'Permanent Resident'), ('Temporary / Transient', 'Temporary / Transient'), ('Transferred Out', 'Transferred Out'), ('Deceased', 'Deceased')], default='Permanent Resident', max_length=40, verbose_name='Residency Status')),
                ('is_pwd', models.BooleanField(default=False, verbose_name='PWD (Person with Disability)')),
                ('is_4ps', models.BooleanField(default=False, verbose_name='4Ps Beneficiary')),
                ('is_single_parent', models.BooleanField(default=False, verbose_name='Single / Solo Parent')),
                ('is_voter', models.BooleanField(default=False, verbose_name='Registered Voter')),
                ('voter_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Voter ID No.')),
                ('blood_type', models.CharField(blank=True, default='N/A', max_length=10, verbose_name='Blood Type')),
                ('purok', models.CharField(blank=True, default='', max_length=150, verbose_name='Purok')),
                ('household_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Household No.')),
                ('household_head', models.CharField(blank=True, default='', max_length=150, verbose_name='Head of Household')),
                ('household_members_count', models.PositiveIntegerField(default=1, verbose_name='Household Members Count')),
                ('gender', models.CharField(blank=True, default='', max_length=10, verbose_name='Gender')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='profiling.household', verbose_name='Household')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Barangay Administrator'), ('Staff', 'Barangay Staff')], default='Staff', max_length=20, verbose_name='Role')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Full Name')),
                ('contact_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Number')),
                ('designation', models.CharField(blank=True, default='Barangay Staff', max_length=100, verbose_name='Designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Complainant / Resident Name')),
                ('contact_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Number')),
                ('purok', models.CharField(blank=True, default='', max_length=100, verbose_name='Purok')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject / Title')),
                ('category', models.CharField(default='General Concern', max_length=100, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description / Details')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=30, verbose_name='Status')),
                ('admin_action_taken', models.TextField(blank=True, default='', verbose_name='Action Taken / Admin Notes')),
                ('action_date', models.DateTimeField(blank=True, null=True, verbose_name='Action Date')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('admin_response', models.TextField(blank=True, default='', verbose_name='Admin Response')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerns', to='profiling.resident', verbose_name='Resident')),
            ],
            options={
                'verbose_name': 'Resident Concern',
                'verbose_name_plural': 'Resident Concerns',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_number', models.CharField(blank=True, default='', max_length=50, verbose_name='O.R. Number')),
                ('document_type', models.CharField(choices=[('Clearance', 'Barangay Clearance'), ('Indigency', 'Certificate of Indigency'), ('Residency', 'Certificate of Residency')], max_length=50, verbose_name='Document Type')),
                ('purpose', models.CharField(max_length=200, verbose_name='Purpose')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid')),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Completed', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Admin Notes / Remarks')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested / Issued')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiling.resident', verbose_name='Resident')),
            ],
            options={
                'verbose_name': 'Document Transaction',
                'verbose_name_plural': 'Document Transactions',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create Record'), ('UPDATE', 'Update Record'), ('DELETE', 'Delete Record'), ('VERIFY', 'Verify Household'), ('PRINT', 'Print Document / ID'), ('LOGIN', 'User Login')], max_length=20, verbose_name='Action Type')),
                ('module_name', models.CharField(max_length=50, verbose_name='Module / Section')),
                ('description', models.TextField(verbose_name='Description / Details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User / Staff')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.CharField(default='General', max_length=50, verbose_name='Category')),
                ('content', models.TextField(verbose_name='Announcement Content')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-date_posted'],
            },
        ),
    ]
