# Generated by Django 4.2.30 on 2026-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='House / Block No.'),
        ),
        migrations.AddField(
            model_name='resident',
            name='household_members_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Members in Household'),
        ),
    ]
