# Generated by Django 4.2.30 on 2026-09-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_resident_house_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='is_voter',
        ),
        migrations.AddField(
            model_name='resident',
            name='household_head',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Head of Household'),
        ),
        migrations.AddField(
            model_name='resident',
            name='household_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Household No.'),
        ),
        migrations.AddField(
            model_name='resident',
            name='relationship_to_head',
            field=models.CharField(choices=[('Head', 'Household Head'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandparent', 'Grandparent'), ('Grandchild', 'Grandchild'), ('Relative', 'Other Relative'), ('Non-Relative', 'Non-Relative / Boarder')], default='Head', max_length=50, verbose_name='Relationship to Head'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='household_members_count',
            field=models.PositiveIntegerField(default=1, verbose_name='No. of Household Members'),
        ),
    ]
