# Generated by Django 4.2.30 on 2026-09-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_remove_resident_house_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_number', models.CharField(max_length=50, unique=True, verbose_name='O.R. Number')),
                ('document_type', models.CharField(choices=[('Clearance', 'Barangay Clearance'), ('Indigency', 'Certificate of Indigency'), ('Residency', 'Certificate of Residency')], max_length=50, verbose_name='Document Type')),
                ('purpose', models.CharField(max_length=200, verbose_name='Purpose')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='Date Issued')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiling.resident', verbose_name='Resident')),
            ],
            options={
                'verbose_name': 'Document Transaction',
                'verbose_name_plural': 'Document Transactions',
                'ordering': ['-date_issued'],
            },
        ),
    ]
