# Generated by Django 4.2.30 on 2026-09-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_documentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlotterCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='Case No.')),
                ('complainant_name', models.CharField(max_length=150, verbose_name='Complainant')),
                ('complainant_address', models.CharField(max_length=255, verbose_name='Complainant Address')),
                ('respondent_name', models.CharField(max_length=150, verbose_name='Respondent')),
                ('respondent_address', models.CharField(max_length=255, verbose_name='Respondent Address')),
                ('incident_type', models.CharField(max_length=100, verbose_name='Incident Type')),
                ('incident_location', models.CharField(blank=True, default='', max_length=255, verbose_name='Incident Location')),
                ('details', models.TextField(blank=True, default='', verbose_name='Complaint Details')),
                ('status', models.CharField(choices=[('Pending', 'Pending Investigation'), ('Scheduled', 'Hearing Scheduled'), ('Settled', 'Settled (Amicable)'), ('Referred', 'Referred to Court')], default='Pending', max_length=30, verbose_name='Status')),
                ('date_filed', models.DateTimeField(auto_now_add=True, verbose_name='Date Filed')),
            ],
            options={
                'verbose_name': 'Blotter Case',
                'verbose_name_plural': 'Blotter Cases',
                'ordering': ['-date_filed'],
            },
        ),
    ]
