# Generated by Django 4.2.30 on 2026-09-25 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiling', '0005_blottercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='admin_notes',
            field=models.TextField(blank=True, default='', verbose_name='Admin Notes / Remarks'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Completed', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Requested / Issued'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='or_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='O.R. Number'),
        ),
        migrations.CreateModel(
            name='ResidentConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('category', models.CharField(default='General Concern', max_length=100, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description / Details')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Pending', max_length=30, verbose_name='Status')),
                ('admin_response', models.TextField(blank=True, default='', verbose_name='Admin Response / Remarks')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='profiling.resident', verbose_name='Resident')),
            ],
            options={
                'verbose_name': 'Resident Concern / Report',
                'verbose_name_plural': 'Resident Concerns & Reports',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.CharField(default='General', max_length=50, verbose_name='Category')),
                ('content', models.TextField(verbose_name='Announcement Content')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-date_posted'],
            },
        ),
    ]
