# Generated by Django 4.2.30 on 2026-09-25 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiling', '0006_documentrequest_admin_notes_documentrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentconcern',
            options={'ordering': ['-date_submitted'], 'verbose_name': 'Resident Concern', 'verbose_name_plural': 'Resident Concerns'},
        ),
        migrations.AddField(
            model_name='resident',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='resident',
            name='educational_attainment',
            field=models.CharField(choices=[('No Formal Education', 'No Formal Education'), ('Elementary Undergraduate', 'Elementary Undergraduate'), ('Elementary Graduate', 'Elementary Graduate'), ('High School Undergraduate', 'High School Undergraduate'), ('High School Graduate', 'High School Graduate'), ('Senior High School', 'Senior High School'), ('Vocational / TVET', 'Vocational / TVET'), ('College Undergraduate', 'College Undergraduate'), ('College Graduate', 'College Graduate (Bachelor)'), ('Post-Graduate', 'Post-Graduate (Master / Doctorate)')], default='High School Graduate', max_length=80, verbose_name='Educational Attainment'),
        ),
        migrations.AddField(
            model_name='resident',
            name='employment_status',
            field=models.CharField(choices=[('Employed (Private)', 'Employed (Private)'), ('Employed (Government)', 'Employed (Government)'), ('Self-Employed / Business', 'Self-Employed / Business'), ('Informal / Daily Wage', 'Informal / Daily Wage'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Retired / Pensioner', 'Retired / Pensioner'), ('Homemaker / Housewife', 'Homemaker / Housewife'), ('OFW', 'Overseas Filipino Worker (OFW)')], default='Employed (Private)', max_length=50, verbose_name='Employment Status'),
        ),
        migrations.AddField(
            model_name='resident',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='resident',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='resident',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='resident',
            name='residency_status',
            field=models.CharField(choices=[('Permanent Resident', 'Permanent Resident'), ('Temporary / Transient', 'Temporary / Transient'), ('Transferred Out', 'Transferred Out'), ('Deceased', 'Deceased')], default='Permanent Resident', max_length=40, verbose_name='Residency Status'),
        ),
        migrations.AddField(
            model_name='resident',
            name='resident_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Resident ID'),
        ),
        migrations.AddField(
            model_name='resident',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='residentconcern',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Action Date'),
        ),
        migrations.AddField(
            model_name='residentconcern',
            name='admin_action_taken',
            field=models.TextField(blank=True, default='', verbose_name='Action Taken / Admin Notes'),
        ),
        migrations.AddField(
            model_name='residentconcern',
            name='complainant_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Complainant / Resident Name'),
        ),
        migrations.AddField(
            model_name='residentconcern',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='residentconcern',
            name='purok',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Purok'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Live-in / Common-law', 'Live-in / Common-law')], default='Single', max_length=30, verbose_name='Civil Status'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='household_members_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Household Members Count'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='occupation',
            field=models.CharField(blank=True, default='N/A', max_length=120, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='purok',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Purok'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='relationship_to_head',
            field=models.CharField(choices=[('Head', 'Household Head'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Relative', 'Other Relative'), ('Non-Relative', 'Non-Relative / Boarder / Househelp')], default='Head', max_length=50, verbose_name='Relationship to Household Head'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='residentconcern',
            name='admin_response',
            field=models.TextField(blank=True, default='', verbose_name='Admin Response'),
        ),
        migrations.AlterField(
            model_name='residentconcern',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerns', to='profiling.resident', verbose_name='Resident'),
        ),
        migrations.AlterField(
            model_name='residentconcern',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='residentconcern',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject / Title'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Barangay Administrator'), ('Staff', 'Barangay Staff')], default='Staff', max_length=20, verbose_name='Role')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Full Name')),
                ('contact_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Number')),
                ('designation', models.CharField(blank=True, default='Barangay Staff', max_length=100, verbose_name='Designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_number', models.CharField(max_length=50, unique=True, verbose_name='Household No. / ID')),
                ('purok', models.CharField(choices=[('Purok 1', 'Purok 1'), ('Purok 2', 'Purok 2'), ('Purok 3', 'Purok 3'), ('Purok 4', 'Purok 4'), ('Purok 5', 'Purok 5'), ('Purok 6', 'Purok 6'), ('Purok 7', 'Purok 7'), ('Purok 8', 'Purok 8'), ('Purok 9', 'Purok 9'), ('Purok 10', 'Purok 10')], max_length=100, verbose_name='Purok')),
                ('complete_address', models.CharField(max_length=255, verbose_name='Complete Address')),
                ('head_name', models.CharField(max_length=150, verbose_name='Householder / Head of Family')),
                ('contact_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Contact Number')),
                ('members_count', models.PositiveIntegerField(default=1, verbose_name='Number of Household Members')),
                ('house_type', models.CharField(choices=[('Concrete', 'Concrete'), ('Semi-Concrete', 'Semi-Concrete'), ('Wood', 'Wood / Timber'), ('Bamboo / Light Materials', 'Bamboo / Nipa / Light Materials'), ('Makeshift / Salvaged', 'Makeshift / Salvaged Materials')], default='Concrete', max_length=50, verbose_name='Type of House')),
                ('housing_ownership', models.CharField(choices=[('Owned (House & Lot)', 'Owned (House & Lot)'), ('Owned House, Rented Lot', 'Owned House, Rented Lot'), ('Rented', 'Rented'), ('Living with Relatives (Rent-free)', 'Living with Relatives (Rent-free)'), ('Rent-free with Consent', 'Rent-free with Owner Consent'), ('Informal Settler', 'Informal Settler')], default='Owned (House & Lot)', max_length=50, verbose_name='Housing Ownership')),
                ('water_source', models.CharField(choices=[('Level III - Piped Water Connection', 'Level III - Piped Water Connection'), ('Level II - Communal Faucet / Deep Well', 'Level II - Communal Faucet / Deep Well'), ('Level I - Protected Well / Spring', 'Level I - Protected Well / Spring'), ('Water Refilling Station / Mineral', 'Water Refilling Station / Mineral'), ('Shared / Dug Well', 'Shared / Dug Well')], default='Level III - Piped Water Connection', max_length=60, verbose_name='Water Source')),
                ('electricity', models.CharField(choices=[('Legal Connection (Utility)', 'Legal Connection (Utility)'), ('Shared Connection / Sub-meter', 'Shared Connection / Sub-meter'), ('Solar Power', 'Solar Power'), ('Generator', 'Generator'), ('None / Kerosene / Candle', 'None / Kerosene / Candle')], default='Legal Connection (Utility)', max_length=50, verbose_name='Electricity')),
                ('toilet_facility', models.CharField(choices=[('Water-sealed Flush', 'Water-sealed Flush (Sewerage/Septic)'), ('Pour-flush Toilet', 'Pour-flush Toilet'), ('Ventilated Improved Pit (VIP)', 'Ventilated Improved Pit (VIP) Latrine'), ('Open Pit Latrine', 'Open Pit Latrine'), ('Shared / Communal Toilet', 'Shared / Communal Toilet'), ('No Toilet Facility', 'No Toilet Facility')], default='Water-sealed Flush', max_length=60, verbose_name='Toilet Facility')),
                ('household_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Relocated', 'Relocated')], default='Active', max_length=30, verbose_name='Household Status')),
                ('verification_status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Verification', 'Pending Verification'), ('Approved', 'Approved'), ('Returned for Correction', 'Returned for Correction')], default='Draft', max_length=30, verbose_name='Verification Status')),
                ('admin_remarks', models.TextField(blank=True, default='', verbose_name='Admin Remarks / Correction Notes')),
                ('date_profiled', models.DateTimeField(auto_now_add=True, verbose_name='Date Profiled')),
                ('date_verified', models.DateTimeField(blank=True, null=True, verbose_name='Date Verified')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('profiled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiled_households', to=settings.AUTH_USER_MODEL, verbose_name='Profiled By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_households', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Household Profile',
                'verbose_name_plural': 'Household Profiles',
                'ordering': ['-date_profiled'],
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='profiling.household', verbose_name='Household'),
        ),
    ]
